default_language_version:
  # default language version for each language
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: name-tests-test


  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            flake8-docstrings,
            flake8-blind-except,
            flake8-bugbear,
            flake8-comprehensions,
            flake8-implicit-str-concat,
            pydocstyle,
            flake8-coding,
            flake8-debugger,
            flake8-deprecated,
            flake8-isort,
            flake8-pep3101,
            flake8-polyfill,
            flake8-print,
            flake8-quotes,
            flake8-string-format,
          ]
        exclude: ^(test_utils/|migrations/|setup\.py)$

  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        files: \.(py|sh|rst|yml|yaml)$
